<?xml version="1.0"?>
<robot
  xmlns:xacro="http://www.ros.org/wiki/xacro" name="kbot">

  <xacro:include filename="$(find kbot_description)/urdf/kbot_gazebo_plugins.xacro"/>

  <!-- aggiunti per il velodyne -->
  <xacro:arg name="gpu" default="false"/>
  <xacro:property name="gpu" value="$(arg gpu)" />
  <xacro:arg name="organize_cloud" default="false"/>
  <xacro:property name="organize_cloud" value="$(arg organize_cloud)" />

  <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
  <xacro:VLP-16 parent="base_link" name="velodyne" topic="/velodyne_points" organize_cloud="${organize_cloud}" hz="10" samples="440" gpu="${gpu}">
    <origin xyz="0 0 0.4" rpy="0 0 0" />
  </xacro:VLP-16>

  <!-- aggiunti per il velodyne -->
 
  <xacro:property name="base_width" value="0.65"/>
  <xacro:property name="base_len" value="1.20"/>
  <xacro:property name="wheel_radius" value="0.07"/>
  <xacro:property name="base_wheel_gap" value="0.007"/>
  <xacro:property name="wheel_separation" value="0.15"/>
  <xacro:property name="wheel_joint_offset" value="0.02"/>
  <xacro:property name="caster_wheel_radius" value="0.03"/>

  <xacro:property name="laser_size_x" value="0.03"/>
  <xacro:property name="laser_size_y" value="0.03"/>
  <xacro:property name="laser_size_z" value="0.04"/>
  <xacro:property name="laser_origin_x" value="0.065"/>
  <xacro:property name="laser_origin_y" value="0"/>
  <xacro:property name="laser_origin_z" value="0.035"/>

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}"/>
    </inertial>
  </xacro:macro>
 
  <link name="base_footprint">
    <xacro:box_inertia m="20" w="0.001" h="0.001" d="0.001"/>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>
 
  <link name="base_link">
    <xacro:box_inertia m="10" w="${base_len}" h="${base_width}" d="0.01"/>
    <visual>
      <geometry>
        <box size="${base_len} ${base_width} 0.01"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_len} ${base_width} 0.01"/>
      </geometry>
    </collision>
  </link>
 
  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius + 0.005}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/> 
    </inertial>
  </xacro:macro>
 
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.005"/>
        </geometry>
	<material name="red"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.005"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="10" r="${wheel_radius}" h="0.005"/>
    </link>
 
    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${wheel_joint_offset} ${((base_width/2)+base_wheel_gap)*reflect} -0.005" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
 
  <xacro:wheel prefix="left" reflect="1"/>
  <xacro:wheel prefix="right" reflect="-1"/>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${2.0*m*(r*r)/5.0}" ixy="0.0" ixz="0.0" iyy="${2.0*m*(r*r)/5.0}" iyz="0.0" izz="${2.0*m*(r*r)/5.0}"/>
    </inertial>
  </xacro:macro>
 
   <link name="caster_wheel1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="5" r="${caster_wheel_radius}"/>
  </link>
 
  <joint name="caster_wheel_joint1" type="continuous">
    <axis xyz="1 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="caster_wheel1"/>
    <origin xyz="-0.5 0.2 -${caster_wheel_radius+0.005}" rpy="0 0 0"/>
  </joint>

  <link name="caster_wheel2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="5" r="${caster_wheel_radius}"/>
  </link>
 
  <joint name="caster_wheel_joint2" type="continuous">
    <axis xyz="1 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="caster_wheel2"/>
    <origin xyz="-0.5 -0.2 -${caster_wheel_radius+0.005}" rpy="0 0 0"/>
  </joint>

<link name="caster_wheel3">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="5" r="${caster_wheel_radius}"/>
  </link>
 
  <joint name="caster_wheel_joint3" type="continuous">
    <axis xyz="1 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="caster_wheel3"/>
    <origin xyz="0.5 0.2 -${caster_wheel_radius+0.005}" rpy="0 0 0"/>
  </joint>

<link name="caster_wheel4">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="5" r="${caster_wheel_radius}"/>
  </link>
 
  <joint name="caster_wheel_joint4" type="continuous">
    <axis xyz="1 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="caster_wheel4"/>
    <origin xyz="0.5 -0.2 -${caster_wheel_radius+0.005}" rpy="0 0 0"/>
  </joint>

  <link name="sensor_laser">
    <!--<visual>
      <geometry>
        <box size="${laser_size_x} ${laser_size_y} ${laser_size_z}"/>
      </geometry>
      <material name="white"/>
    </visual> -->
    <visual>
     <geometry>
       <mesh filename="package://kbot_description/meshes/hokuyo.dae"/>
     </geometry>
   </visual>
    <collision>
      <geometry>
        <box size="${laser_size_x} ${laser_size_y} ${laser_size_z}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.2" w="${laser_size_x}" h="${laser_size_y}" d="${laser_size_z}"/>
  </link>

  <gazebo reference="sensor_laser">
    <sensor type="ray" name="laser_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.75</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_laser.so">
        <topicName>/kbot/sensor_laser/scan</topicName>
        <frameName>sensor_laser</frameName>
      </plugin>
    </sensor>
  </gazebo>
 
  <joint name="sensor_laser_joint" type="fixed">
    <origin xyz="${laser_origin_x} ${laser_origin_y} ${laser_origin_z}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="sensor_laser" />
  </joint>



</robot>
